### ISSUE TITLE
result

### ISSUE THREAD

**Issue by Tiandishihua** [sail-sg/Consistent3D#1]
Is the result a mesh with textures and colors?

**Comment by yxymessi** [comment]
> Is the result a mesh with textures and colors?

The mesh can be explored.

**Comment by nickwzk** [comment]
Hi @Tiandishihua,
Thank you for your interest in our work. We do support mesh export with the generated results. For detailed guidance on exporting meshes, please refer to the updated instructions in [README](https://github.com/sail-sg/Consistent3D?tab=readme-ov-file#export-mesh).
