### ISSUE TITLE
where can i get the pretrained model?

### ISSUE THREAD

**Issue by chengfengke** [sail-sg/Consistent3D#3]
I have not noticed any information about the pretrianed model or the training scripts, where can i get it.

**Comment by yxymessi** [comment]
> I have not noticed any information about the pretrianed model or the training scripts, where can i get it.

Consistent3D is a optimization-based 3D generation pipeline, which means we leverage the **pretrained** 2D diffusion model to generate 3D assets. The training scripts have already been introduced in the readme file.

**Comment by chengfengke** [comment]
> > I have not noticed any information about the pretrianed model or the training scripts, where can i get it.
> 
> Consistent3D is a optimization-based 3D generation pipeline, which means we leverage the **pretrained** 2D diffusion model to generate 3D assets. The training scripts have already been introduced in the readme file.

thank you，I've already got the retrained model on the Huggingface.
