### ISSUE TITLE
Additional Loss term compared with paper

### ISSUE THREAD

**Issue by zcai0612** [sail-sg/Consistent3D#4]
May I ask about the first term of the loss function? `(sigma_t / (sigma_t_next + 1e-9)) * (pred_epsilon - noise_pred)` It seems that it always equals zero.

https://github.com/sail-sg/Consistent3D/blob/9118a5cc8ba4d16aa1c092301aedffb68c31f18e/threestudio/models/guidance/stable_diffusion_guidance.py#L394

**Comment by nickwzk** [comment]
It is borrowed from [Common Diffusion Noise Schedules and Sample Steps Are Flawed](https://openaccess.thecvf.com/content/WACV2024/html/Lin_Common_Diffusion_Noise_Schedules_and_Sample_Steps_Are_Flawed_WACV_2024_paper.html). You can optionally activate it by setting _"recon_std_rescale"_ to non-zero integers. However, we found it not suitable in our work, so we set this rescale to zero as default.
