### ISSUE TITLE
Can not run inference on a single RTX3090

### ISSUE THREAD

**Issue by Colezwhy** [sail-sg/Consistent3D#6]
Thank you for your great job, but when I want to run inference on one single RTX3090, I got out of memory.
Would you please provide some suggestions?

**Comment by nickwzk** [comment]
Hi @Colezwhy,
Thank you for your interest in our work. You can simply try to reduce **_batch_size_** to 4 in the configs to reduce the memory cost.

**Comment by Colezwhy** [comment]
> Hi @Colezwhy, Thank you for your interest in our work. You can simply try to reduce **_batch_size_** to 4 in the configs to reduce the memory cost.

Thank you, I will try.
